### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by 1525513874** [TranslationalBioinformaticsUnit/GeneSetCluster#5]
Hello, 
I encountered some errors that prevented the package from being installed properly.
And there are the following errors.

#############################################################################################
* checking for file 'C:\Users\12074\AppData\Local\Temp\Rtmp820kZw\remotes208027996ba5\TranslationalBioinformaticsUnit-GeneSetCluster-0d45ff6/DESCRIPTION' ... OK
* preparing 'GeneSetCluster':
* checking DESCRIPTION meta-information ... OK
* checking vignette meta-information ... OK
* excluding invalid files
Subdirectory 'R' contains invalid file names:
  'GeneSetCluster.pipeline' 'GenesPerGeneset.Count.fc' 'RR_stats'
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'GeneSetCluster_1.2.1.tar.gz'
* installing *source* package 'GeneSetCluster' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import 'clusterProfiler::filter' by 'stats::filter' when loading 'GeneSetCluster'
in method for 'GenesPerGeneSet' with signature '"PathwayObject"': no definition for class "PathwayObject"
Error in eval(exprs[i], envir) : 
  object 'PBMC.RTX.HCvsBS_BSvsBS.Age.Sex.Duration' not found
Error: unable to load R code in package 'GeneSetCluster'
Execution halted
ERROR: lazy loading failed for package 'GeneSetCluster'
* removing 'D:/bbbioinformatics/R/R-4.2.1/library/GeneSetCluster'
###########################################################################################

I hope you can help me solve this problem.
Thanks a lot.

Jackson

**Comment by EwoudEwing** [comment]
Hej Jackson,

I see that a bit of test code made it into one of the functions which calls for object 'PBMC.RTX.HCvsBS_BSvsBS.Age.Sex.Duration'  This isnt in the files so it gives an error. I removed this code. Try again :)

Best,
Ewoud

**Comment by 1525513874** [comment]
Now it's like this.
（I tried it in both versions 4.2.2 and 4.2.1 of R.）

#########################################################################################
* installing *source* package 'GeneSetCluster' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/12074/AppData/Local/Temp/RtmpQLZzdz/R.INSTALL4ab4421c77bb/GeneSetCluster/R/ORA2ObjectFromList.R:119:2: unexpected symbol
118: #Data$L1$Gene <- as.character(probe.features.merged[rownames(Data$L1),"gene"])
119: 3Data
      ^
ERROR: unable to collate and parse R files for package 'GeneSetCluster'
* removing 'D:/bbbioinformatics/R/R-4.2.2/library/GeneSetCluster'
##########################################################################################

**Comment by EwoudEwing** [comment]
Try again, I removed the function (its still in testing).

/Ewoud

**Comment by 1525513874** [comment]
Now I successfully installed it.


Thank you very much.
Jackson

**Comment by EwoudEwing** [comment]
Great! Let me know if you have more issues :)

/Ewoud
